--- name:default
# bias offset in static regimen for the Accelerometers
abiasof: 
  data: 
  - -0.0125
  - 0.00908
  - -0.03531
# acceleration random walk for accelerometers (m/s^2/sqrt(s))
accrrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# velocity random walk for accelerometers (m/s/sqrt(s))
accrw: 
  data: 
  - 0.00150 #0.0009858879
  - 0.00150 #0.001097635
  - 0.00150 #0.001070773
# Altitude of Bremen in meters
altitude: 12.0
# the global name that should be used for the internal body frame
body_frame: body
# Time in s between calibrated_sensors readings
calibrated_sensors_period: 0.008
# Dip angle of Bremen in radians (equivalent to 68.05 degrees ).
dip_angle: 1.187696556
# Eccentricity (in meters) for X-axis Acc in IMU frame (with respect to the IMU reference frame).
eccx: 
  data: 
  - -0.03347
  - -0.02490
  - 0.01750
# Eccentricity (in meters) for Y-axis Acc in IMU frame (with respect to the IMU reference frame).
eccy: 
  data: 
  - -0.00867
  - -0.00517
  - 0.01178
# Eccentricity (in meters) for Z-axis Acc in IMU frame (with respect to the IMU reference frame).
eccz: 
  data: 
  - -0.01292
  - -0.01603
  - 0.00681
# Quaternion to specify the projection of the center of mass to the rover X-Y plane (center of gravity).Identity quaternion if the weight is equally distributed.
#corresponding to asguard uneven weight distribution (roll=0.00, pitch=+18.26 and yaw=0.00)
q_weight_distribution:
  re: 0.987331
  im:
  - 0.0
  - 0.158675
  - 0.0
# Desired frequency in Hertz to run the filter. It cannnot be bigger that the sensor values of the aggregator (transformer)
filter_frequency: 100.0
# bias offset in static regimen for the Gyroscopes
gbiasof: 
  data: 
  - 0.0 #3.1396251683848041e-05
  - 0.0 #0.0004564014580275626
  - 0.0 #-0.00045970399412453427
# Time in s between ground_forces_estimated readings
ground_forces_estimated_period: 0.01
# rate random walk for gyroscopes (rad/s/sqrt(s))
gyrorrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# angle random walk for gyroscopes (rad/sqrt(s))
gyrorw: 
  data: 
  - 7.0e-05 #4.320343e-05
  - 7.0e-05 #4.175001e-05
  - 7.0e-05 #4.060973e-05
# Time in s between hbridge_samples readings
hbridge_samples_period: 0.001
# the global name that should be used for the internal imu frame
imu_frame: imu
# Latitude of Bremen in radians (equivalent to 53.083333 degrees).
latitude: 0.926478944
# Longitude of Bremen in radians (equivalent to 8.8 degrees).
longitude: 0.153588974
# Bremen magnetic declination in radians (equivalent to 1.35 degrees EAST).
magnetic_declination: 0.023561944
# The declination is positive when the magnetic north is east of true north
magnetic_declination_mode: 1
# random walk for magnetometers
magrw: 
  data: 
  - 0.0
  - 0.0
  - 0.0
# Time in s between orientation_init readings
pose_init_period: 0.01
# Inertial sensors bandwidth in Hertz. This is characteristic of the sensor and should be equal or smaller than the sampling rate.
sensors_bandwidth: 16.0
# list of static transformations
static_transformations: []
# Time in s between systemstate_samples readings
systemstate_samples_period: 0.01
# Time in s between torque_estimated readings
torque_estimated_period: 0.01
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
