--- name:default
# the global name that should be used for the internal body frame
body_frame: body

# the global name that should be used for the internal imu frame
imu_frame: imu

# the global name that should be used for the internal vicon frame
vicon_frame: vicon

# Eccentricity (in meters) for X-axis Acc in IMU frame (with respect to the IMU reference frame).
eccx:
  data:
  - -0.03347
  - -0.02490
  - 0.01750
# Eccentricity (in meters) for Y-axis Acc in IMU frame (with respect to the IMU reference frame).
eccy:
  data:
  - -0.00867
  - -0.00517
  - 0.01178
# Eccentricity (in meters) for Z-axis Acc in IMU frame (with respect to the IMU reference frame).
eccz:
  data:
  - -0.01292
  - -0.01603
  - 0.00681

# Initial configuration values to run the framework. Look in FrameworkTypes for further details.
framework:
  frontend_frequency: 100.0 #Hertz
  backend_frequency: 10.0 #Hertz
  visualization_frequency: 100.0 #Herts
  use_inclinometers_leveling: true
  init_leveling_time: 5.0 #Hertz

# Localization properties related to the geograohic place (i.e: latitudem longitude, magnetic declination).Look in FrameworkTypes for further details
location:
  latitude: 0.926478944
  longitude: 0.153588974
  altitude: 12.0
  magnetic_declination: 0.023561944
  magnetic_declination_mode: 1
  dip_angle: 1.187696556

# Proprioceptive Sensors property. It contains the inertial and encoder sensor characterization.
proprioceptive_sensors:
  bandwidth: 0.0
  gbiasof:
    data:
    - 0.0 #3.1396251683848041e-05
    - 0.0 #0.0004564014580275626
    - 0.0 #-0.00045970399412453427
  gyrorw:
    data:
    - 7.0e-05 #4.320343e-05
    - 7.0e-05 #4.175001e-05
    - 7.0e-05 #4.060973e-05
  gyrorrw:
    data:
    - 0.0
    - 0.0
    - 0.0
  gbiasins:
    data:
    - 6.882191e-06
    - 8.479295e-06
    - 5.591609e-06
  abiasoff:
    data:
    - 0.0 #-0.0027
    - 0.0 
    - 0.0 #0.0055
  accrw:
    data:
    - 0.00150 #0.0009858879
    - 0.00150 #0.001097635
    - 0.00150 #0.001070773
  accrrw:
    data:
    - 0.0
    - 0.0
    - 0.0
  abiasins:
    data:
    - 0.0005639343
    - 0.0006412585
    - 0.0005866994
  magrw:
    data:
    - 0.0
    - 0.0
    - 0.0

# Time in s between pose_init_samples readings
pose_init_samples_period: 0.01
# Time in s between inertial_samples readings
inertial_samples_period: 0.002
# Time in s between torque_samples readings
torque_samples_period: 0.01
# Time in s between ground_forces_samples readings
ground_forces_samples_period: 0.01
# Time in s between systemstate_samples readings
systemstate_samples_period: 0.01
# Time in s between encoder_samples readings
encoder_samples_period: 0.001

# Quaternion to specify the projection of the center of mass to the rover X-Y plane (center of gravity).Identity quaternion means the weight is equally distributed.
q_weight_distribution:
  im:
  - 0.0
  - 0.07201969328078207 #0.158675 #Whitout GPS
  - 0.0
  re: 0.9974032102313197 #0.987331 #Whitout GPS

# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0

