--- name:default
# Initial configuration values to run the framework. Look in FrameworkTypes for further details.
framework:
  frontend_frequency: 100.0
  backend_frequency: 10.0
  visualization_frequency: 100.0
  use_inclinometers_leveling: true
  init_leveling_time: 5.0

# Time in s between exteroceptive_samples readings
exteroceptive_samples_period: 0.01
# Time in s between pose_samples readings
pose_samples_period: 0.01
# Time in s between inertial_samples readings
inertial_samples_period: 0.01

# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.5
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
# Time in s between update_samples readings
update_samples_period: 0.01

--- name:stim300
# Proprioceptive Sensors property. It contains the inertial and encoder sensor characterization.Look in FrameworkTypes for further details
proprioceptive_sensors:
  bandwidth: 131.0 #Hertz
  gbiasoff:
    data:
    - 0.0 #3.1396251683848041e-05
    - 0.0 #0.0004564014580275626
    - 0.0 #-0.00045970399412453427
  gyrorw:
    data:
    - 7.0e-05 #4.320343e-05
    - 7.0e-05 #4.175001e-05
    - 7.0e-05 #4.060973e-05
  gyrorrw:
    data:
    - 0.0
    - 0.0
    - 0.0
  gbiasins:
    data:
    - 6.882191e-06
    - 8.479295e-06
    - 5.591609e-06
  abiasoff:
    data:
    - 0.0 #-0.0027
    - 0.0 
    - 0.0 #0.0055
  accrw:
    data:
    - 0.00150 #0.0009858879
    - 0.00150 #0.001097635
    - 0.00150 #0.001070773
  accrrw:
    data:
    - 0.0
    - 0.0
    - 0.0
  abiasins:
    data:
    - 0.0005639343
    - 0.0006412585
    - 0.0005866994
  magrw:
    data:
    - 0.0
    - 0.0
    - 0.0

# Properties for the adaptive estimation of external acceleration. Look in FrameworkTypes for further details.
adaptive_filter:
  M1: 1 #Parameter for adaptive algorithm (to estimate Uk which is not directly observale)
  M2: 5 #Parameter for adaptive algorithm (to prevent falsering entering in no-external acc mode)
        #If it previously is in external-acc mode. It needs at least M2 consecutive times to exit and enter in non-external-acc mode
  gamma: 0.0005 #Parameter for adaptive algorithm (only entering when Qstart is this value greater than HPH'+Ra)
                #This is to prevent that the external acc noise cov is affected by normal acc fructuation
  r2count: 100 #Parameter for adaptive algorithm (No enterring r2count times at the begining )when enetring once r2count is set to zero.

